services:
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/talentbridge
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 18112005
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
