server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/database}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your_email@gmail.com}
    password: ${MAIL_PASSWORD:your_app_password}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
    web:
      pageable:
        one-indexed-parameters: true

  config:
    import: file:.env[.properties]

jwt:
  secret: "${JWT_SECRET:your_jwt_secret_key_minimum_256_bits_length_for_security}"
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:300}
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:86400}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:your_cloud_name}
  api-key: ${CLOUDINARY_API_KEY:your_api_key}
  api-secret: ${CLOUDINARY_API_SECRET:your_api_secret}
