create table if not exists companies
(
    id          bigint generated by default as identity,
    created_at  timestamp(6) with time zone,
    created_by  varchar(255),
    is_deleted  boolean not null,
    modified_by varchar(255),
    updated_at  timestamp(6) with time zone,
    address     varchar(255),
    description text,
    job_count   integer,
    name        varchar(255),
    logo_id     bigint,
    owner_id    bigint
);

alter table companies
    add primary key (id);

alter table companies
    add constraint ukjeqid97mh9x6fa7edphxcpfia
        unique (logo_id);

alter table companies
    add constraint uk2xrywqtkk3tty82u66fs3s7gm
        unique (owner_id);

create table if not exists company_logos
(
    id          bigint generated by default as identity,
    file_id     varchar(255),
    file_size   bigint,
    file_type   varchar(255),
    file_url    varchar(255),
    uploaded_at timestamp(6) with time zone
);

alter table company_logos
    add primary key (id);

alter table companies
    add constraint fk465cr2wfnvae1440c8koeslgb
        foreign key (logo_id) references company_logos;

create table if not exists email_task
(
    id            bigint generated by default as identity,
    created_at    timestamp(6) with time zone,
    created_by    varchar(255),
    is_deleted    boolean      not null,
    modified_by   varchar(255),
    updated_at    timestamp(6) with time zone,
    error_message text,
    next_retry_at timestamp(6) with time zone,
    retry_count   integer      not null,
    send_date     date         not null,
    status        varchar(255) not null,
    email       varchar(255)       not null
);

create index if not exists idx_email_task_status_retry
    on email_task (status, next_retry_at) where status = 'PENDING';

alter table email_task
    add primary key (id);

alter table email_task
    add constraint ukra1pslbrclu5wg4oli0cjkgmw
        unique (email, send_date);

alter table email_task
    add constraint email_task_status_check
        check ((status)::text = ANY
               ((ARRAY ['PENDING'::character varying, 'PROCESSING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[]));


CREATE INDEX idx_email_task
    ON email_task(email);

-- Index for date-based queries
CREATE INDEX idx_email_task_send_date
    ON email_task(send_date);

-- Create trigger to update updated_at automatically
CREATE OR REPLACE FUNCTION update_email_task_timestamp()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_email_task_update_timestamp
    BEFORE UPDATE ON email_task
    FOR EACH ROW
EXECUTE FUNCTION update_email_task_timestamp();


create table if not exists email_verification_token
(
    id         bigint generated by default as identity,
    expired_at timestamp(6) with time zone,
    token      varchar(255),
    used       boolean not null,
    user_id    bigint
);

alter table email_verification_token
    add primary key (id);

alter table email_verification_token
    add constraint uk1sxbwflvq4skafkocq315i9dt
        unique (user_id);

create table if not exists job_applications
(
    id           bigint generated by default as identity,
    created_at   timestamp(6) with time zone,
    created_by   varchar(255),
    is_deleted   boolean not null,
    modified_by  varchar(255),
    updated_at   timestamp(6) with time zone,
    cover_letter text,
    cv_file_id   varchar(255),
    cv_file_name varchar(255),
    cv_file_url  varchar(255),
    email        varchar(255),
    name         varchar(255),
    phone_number varchar(255),
    status       varchar(255),
    version      bigint,
    job_id       bigint,
    user_id      bigint
);

alter table job_applications
    add primary key (id);

alter table job_applications
    add constraint job_applications_status_check
        check ((status)::text = ANY
               ((ARRAY ['PENDING'::character varying, 'REVIEWING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[]));

create table if not exists jobs
(
    id          bigint generated by default as identity,
    active      boolean          not null,
    description text,
    end_date    timestamp(6) with time zone,
    level       varchar(255),
    location    varchar(255),
    name        varchar(255),
    quantity    integer,
    salary      double precision not null,
    start_date  timestamp(6) with time zone,
    company_id  bigint           not null
);

alter table jobs
    add primary key (id);

alter table job_applications
    add constraint fkqt4m3c9yiioi16kwsyjrl0cpl
        foreign key (job_id) references jobs;

alter table jobs
    add constraint fkrtmqcrktb6s7xq8djbs2a2war
        foreign key (company_id) references companies;

alter table jobs
    add constraint jobs_level_check
        check ((level)::text = ANY
               ((ARRAY ['NONE'::character varying, 'UNDER_ONE_YEAR'::character varying, 'ONE_YEAR'::character varying, 'TWO_YEARS'::character varying, 'THREE_YEARS'::character varying, 'FOUR_YEARS'::character varying, 'FIVE_YEARS'::character varying, 'OVER_FIVE_YEARS'::character varying])::text[]));

create table if not exists jobs_skills
(
    job_id   bigint not null,
    skill_id bigint not null
);

alter table jobs_skills
    add constraint fk5lnk82o1wgsar3sa67ljg430i
        foreign key (job_id) references jobs;

create table if not exists permission
(
    id          bigint generated by default as identity,
    created_at  timestamp(6) with time zone,
    created_by  varchar(255),
    is_deleted  boolean not null,
    modified_by varchar(255),
    updated_at  timestamp(6) with time zone,
    api_path    varchar(255),
    description text,
    method      varchar(255),
    module      varchar(255),
    name        varchar(255)
);

alter table permission
    add primary key (id);

create table if not exists refresh_token
(
    jti                  varchar(255) not null,
    device_name          varchar(255),
    device_type          varchar(255),
    expiration_date_time timestamp(6) with time zone,
    is_revoked           boolean      not null,
    token                varchar(255),
    user_agent           varchar(255),
    user_id              bigint
);

alter table refresh_token
    add primary key (jti);

create table if not exists resumes
(
    id          bigint generated by default as identity,
    created_at  timestamp(6) with time zone,
    created_by  varchar(255),
    is_deleted  boolean not null,
    modified_by varchar(255),
    updated_at  timestamp(6) with time zone,
    file_id     varchar(255),
    file_url    varchar(255),
    name        varchar(255),
    user_id     bigint
);

alter table resumes
    add primary key (id);

create table if not exists role
(
    id          bigint generated by default as identity,
    created_at  timestamp(6) with time zone,
    created_by  varchar(255),
    is_deleted  boolean not null,
    modified_by varchar(255),
    updated_at  timestamp(6) with time zone,
    active      boolean not null,
    description varchar(255),
    name        varchar(255)
);

alter table role
    add primary key (id);

create table if not exists roles_permissions
(
    role_id       bigint not null,
    permission_id bigint not null
);

alter table roles_permissions
    add primary key (role_id, permission_id);

alter table roles_permissions
    add constraint fkboeuhl31go7wer3bpy6so7exi
        foreign key (permission_id) references permission;

alter table roles_permissions
    add constraint fk4hrolwj4ned5i7qe8kyiaak6m
        foreign key (role_id) references role;

create table if not exists skills
(
    id          bigint generated by default as identity,
    created_at  timestamp(6) with time zone,
    created_by  varchar(255),
    is_deleted  boolean not null,
    modified_by varchar(255),
    updated_at  timestamp(6) with time zone,
    name        varchar(255)
);

alter table skills
    add primary key (id);

alter table jobs_skills
    add constraint fkil3ayyhf80asgae5q2iega9vg
        foreign key (skill_id) references skills;

create table if not exists skills_jobs
(
    skill_id bigint not null,
    jobs_id  bigint not null
);

alter table skills_jobs
    add constraint fk7otetemjtvvvirpvjf56krfq1
        foreign key (jobs_id) references jobs;

alter table skills_jobs
    add constraint fkqf6a2cc3peoxftrlvkcr8s1qx
        foreign key (skill_id) references skills;

create table if not exists subscribers
(
    id                bigint generated by default as identity,
    created_at        timestamp(6) with time zone,
    created_by        varchar(255),
    is_deleted        boolean not null,
    modified_by       varchar(255),
    updated_at        timestamp(6) with time zone,
    email             varchar(255),
    expected_salary   double precision,
    level             varchar(255)
);

alter table subscribers
    add primary key (id);

alter table subscribers
    add constraint subscribers_level_check
        check ((level)::text = ANY
               ((ARRAY ['NONE'::character varying, 'UNDER_ONE_YEAR'::character varying, 'ONE_YEAR'::character varying, 'TWO_YEARS'::character varying, 'THREE_YEARS'::character varying, 'FOUR_YEARS'::character varying, 'FIVE_YEARS'::character varying, 'OVER_FIVE_YEARS'::character varying])::text[]));

create table if not exists subscribers_skills
(
    subscriber_id bigint not null,
    skill_id      bigint not null
);

alter table subscribers_skills
    add constraint fkakdyio4yg7mv3i1dte91xlepi
        foreign key (skill_id) references skills;

alter table subscribers_skills
    add constraint fkgfy8nwkyd7sw3ff4mp5swht8
        foreign key (subscriber_id) references subscribers;

create table if not exists users
(
    id             bigint generated by default as identity,
    created_at     timestamp(6) with time zone,
    created_by     varchar(255),
    is_deleted     boolean not null,
    modified_by    varchar(255),
    updated_at     timestamp(6) with time zone,
    address        varchar(255),
    avatar_url     varchar(255),
    dob            date,
    email          varchar(255),
    email_verified boolean not null,
    full_name      varchar(255),
    gender         varchar(255),
    password       varchar(255),
    status         varchar(255),
    company_id     bigint,
    role_id        bigint
);

alter table users
    add primary key (id);

alter table companies
    add constraint fkikhsc7na5r394c8jghny8b6t4
        foreign key (owner_id) references users;

alter table email_verification_token
    add constraint fkknax5in7pcatm2uf9uyple35x
        foreign key (user_id) references users;

alter table job_applications
    add constraint fkqs2guhg7p83917vto86imuthy
        foreign key (user_id) references users;

alter table refresh_token
    add constraint fkjtx87i0jvq2svedphegvdwcuy
        foreign key (user_id) references users;

alter table resumes
    add constraint fk340nuaivxiy99hslr3sdydfvv
        foreign key (user_id) references users;

alter table users
    add constraint fkin8gn4o1hpiwe6qe4ey7ykwq7
        foreign key (company_id) references companies;

alter table users
    add constraint fk4qu1gr772nnf6ve5af002rwya
        foreign key (role_id) references role;

alter table users
    add constraint users_gender_check
        check ((gender)::text = ANY
               ((ARRAY ['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying])::text[]));

alter table users
    add constraint users_status_check
        check ((status)::text = ANY
               ((ARRAY ['PENDING'::character varying, 'ACTIVE'::character varying, 'IN_ACTIVE'::character varying])::text[]));

create function update_company_job_count()  returns trigger
    language plpgsql
as
$$
BEGIN
    IF TG_OP = 'INSERT' THEN
UPDATE companies
SET job_count = job_count + 1
WHERE id = NEW.company_id;

ELSIF TG_OP = 'DELETE' THEN
UPDATE companies
SET job_count = job_count - 1
WHERE id = OLD.company_id;
END IF;

RETURN NULL;
END;
$$;

